
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: charm-0
spec:
  slotsPerWorker: 1
  priority: 1
  runLauncherAsWorker: true
  runPolicy:
    cleanPodPolicy: Running
    ttlSecondsAfterFinished: 600
  sshAuthMountPath: /home/mpiuser/.ssh
  mpiReplicaSpecs:
    Launcher:
      maxReplicas: 1
      template:
        spec:
          containers:
          - image: adityapb/charm-mpi:latest
            imagePullPolicy: Always
            name: mpi-launcher
            securityContext:
              runAsUser: 1000
            command:
            - /app/charmrun_elastic
            args:
            - /app/jacobi2d
            - "32768"
            - "512"
            - "10000"
            - +balancer
            - GreedyCentralLB
            - +LBDebug
            - "3"
            resources:
              limits:
                cpu: 1
            volumeMounts:
            - mountPath: /dev/shm
              name: shm-volume
          volumes:
          - name: shm-volume
            emptyDir:
              medium: Memory
              sizeLimit: 1.5Gi
    Worker:
      minReplicas: 15
      maxReplicas: 59
      template:
        spec:
          containers:
          - image: adityapb/charm-mpi:latest
            imagePullPolicy: Always
            name: mpi-worker
            volumeMounts:
            - mountPath: /dev/shm
              name: shm-volume
            securityContext:
              runAsUser: 1000
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            resources:
              limits:
                cpu: 1
          volumes:
            - name: shm-volume
              emptyDir:
                medium: Memory
                sizeLimit: 1.5Gi
